# k8s-automation/group_vars/all.yml
# Central configuration for the Kubernetes cluster

cluster_topology:
  # --- YOUR EXISTING PRIMARY ACCOUNT ---
  # These nodes already exist. Ansible will NOT recreate them, it will just 
  # verify they are running, and use their IPs to build the WireGuard mesh!
  
  - type: "master"
    count: 3
    project: "project_id"
    zone: "asia-southeast1-a"
    machine_type: "e2-standard-2"
  
  - type: "worker"
    count: 2
    project: "project_id0"
    zone: "asia-southeast2-a"
    machine_type: "e2-standard-2"

  # --- YOUR NEW SECONDARY ACCOUNT ---
  # These nodes do not exist yet. Ansible will create them from scratch.
  
  - type: "worker"
    count: 3
    project: "project_id"
    zone: "asia-southeast1-b"
    machine_type: "custom-4-8192"

wireguard:
  mesh_cidr: "10.200.0.0/24"
  port: 51820
