[all:vars]
ansible_user=alexkgm
ansible_ssh_private_key_file=~/.ssh/google_compute_engine
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3

[all]
master1-k8s ansible_host=34.21.148.185 ip=10.200.0.1 access_ip=10.200.0.1
master2-k8s ansible_host=34.142.163.150 ip=10.200.0.2 access_ip=10.200.0.2
master3-k8s ansible_host=34.126.79.255 ip=10.200.0.3 access_ip=10.200.0.3
worker1-k8s ansible_host=34.101.154.249 ip=10.200.0.4 access_ip=10.200.0.4
worker2-k8s ansible_host=34.50.101.228 ip=10.200.0.5 access_ip=10.200.0.5
worker3-k8s ansible_host=34.126.191.101 ip=10.200.0.6 access_ip=10.200.0.6
worker4-k8s ansible_host=34.87.35.12 ip=10.200.0.7 access_ip=10.200.0.7
worker5-k8s ansible_host=34.142.166.43 ip=10.200.0.8 access_ip=10.200.0.8

[kube_control_plane]
master1-k8s
master2-k8s
master3-k8s

[etcd]
master1-k8s
master2-k8s
master3-k8s

[kube_node]
master1-k8s
master2-k8s
master3-k8s
worker1-k8s
worker2-k8s
worker3-k8s
worker4-k8s
worker5-k8s

[k8s_cluster:children]
kube_control_plane
kube_node

[calico_rr]
