apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault-itp.autonomous-istad.com"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token-secret
          key: token
          namespace: external-secrets
